name: kebab
description: A new Flutter project.

publish_to: 'none' 


version: 0.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.2.9
  font_awesome_flutter: ^10.2.1
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_lorem: ^2.0.0
  


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#f7c72a"
  image: assets/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/ca/
    - assets/images/


 